python:
  - "3.6"

before_install:
  - pip install --upgrade pip
  - pip install --user codecov
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - codecov --file coverage/lcov.info --disable search