python:
  - "3.4"
virtualenv:
  system_site_packages: true

before_install:
  - pip install pytest-cov

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=./

after_success:
  - codecov --file coverage/lcov.info --disable search