python:
  - "3.4"
virtualenv:
  system_site_packages: true

requirements:
  - pip install -r requirements.txt

before_install:
  - pip install --user codecov

script:
  - pytest

after_success:
  - codecov --file coverage/lcov.info --disable search